#Habilita o endpoint /actuator/beans
management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: covid-metrics
  data.mongodb:
    host : localhost
    port : 27017
    database : covid
  rabbitmq:
    host: localhost
    port: 5672
    dynamic: true
    username: guest
    password: guest

api-covid:
  endpoint: https://api.covid19api.com
  countriesRoute: /countries
  countryDayOneRoute: /dayone/country/{country}
  countryStatusLiveRoute: /country/{country}/status/{status}/live
  countryDayOneTotalRoute: /total/dayone/country/{country}

covid-firebase:
  url: http://localhost:8081
  put-covid-id: /v1/covid/{id}/firebase

server:
  port: 8080

